### PR TITLE
fix: Not running final build command

### LINKED ISSUE #5: Parent package stand-alone build fail in v1.1.0 when use pnpm
I noticed weird behavior in the wxt monorepo……when do a stand-alone build of `packages/wxt` the build doesn't run (using `pnpm --filter wxt build`, for example).

I looked at the logs and looks like the result of this line here have changed, something must have been broken in the 1.1.0 bun support.
https://github.com/aklinker1/buildc/blob/8564179c53d0fa943133b0a0533fd0f896ef25a6/src/index.ts#L49-L50

In wxt monorepo, it's not completely stuck, because we can avoid by `pnpm i` in root. So no urgent action is needed. This is just a report 🙏

### PR DESCRIPTION
**Pull request by aklinker1**
This closes #5

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -57,20 +57,22 @@ export async function buildPackage(
   // delete directories.
   await withLock(monorepo.cacheDir, async () => {
     for (const pkg of packages) {
-      await buildCached(
-        monorepo,
-        pkg,
-        pkg === targetPkg
```
Comment (aklinker1) [inline src/index.ts:63]: `pkg` is never equal to `targetPkg` now that we're using `dependenciesOf`.

File: src/index.ts [hunk 2]
```diff
@@ -40,14 +44,10 @@ export async function buildPackage(
   consola.debug("Target package:", targetPkg);
 
   const graph = buildMonorepoGraph(monorepo);
-  // Remove unrelated deps from graph
-  graph.entryNodes().forEach((entry) => {
-    if (entry !== targetPkg.name) graph.removeNode(entry);
-  });
```
Comment (aklinker1) [inline src/index.ts:46]: `getPackageDependenciesBuildOrder` (`graph.dependenciesOf`) does this for us.
